In [1]:
import numpy as np

In [2]:
A = [[1,1,0],[1,0,0],[1,1,1]]
A = np.array(A,dtype = float)

In [5]:
s = []
for i in range(len(A[0])):
    s.append(np.sum(A[:,i]))
s

[3.0, 2.0, 1.0]

In [7]:
M = np.empty(np.shape(A))
for i in range(len(A[0])):
    for j in range(len(A)):
        M[j][i] = A[j][i]/s[i]
M

array([[0.33333333, 0.5       , 0.        ],
       [0.33333333, 0.        , 0.        ],
       [0.33333333, 0.5       , 1.        ]])

In [9]:
# Removing Dangling Node
d = np.empty(np.shape(M))
for i in range(len(d)):
    for j in range(len(d[0])):
        d[i][j] = 1/len(M)
dm = (1-0.15)*M + 0.15*d

In [10]:
dm

array([[0.33333333, 0.475     , 0.05      ],
       [0.33333333, 0.05      , 0.05      ],
       [0.33333333, 0.475     , 0.9       ]])

In [11]:
e_values  , e_vectors = np.linalg.eig(dm)

In [13]:
e_vectors[0]

array([0.14754318, 0.51994159, 0.6295454 ])